# docker file adds certbot to container
FROM hiltonbanes/wintercms:php7.4-apache

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	ssl-cert \
	certbot \
	python3-certbot-apache \
	at && \
	rm -rf /var/lib/apt/lists/*

RUN a2enmod ssl; \
	a2ensite default-ssl;

EXPOSE 443

COPY ./certbot-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["certbot-entrypoint.sh"]
CMD ["apache2-foreground"]
